### ISSUE TITLE
Re: Metadata of Face and adding secondary classifiers

### ISSUE THREAD

**Issue by rohitnairkp** [aj-ames/Centerface-Deepstream#1]
Hi @aj-ames,

Your works are amazing. I came across some of your deepstream related works which showing only the detection part.Can you make some tutorial or guide on how to access the metadata from the detected objects like face, person, or any other object. It would be really helpful.

**Comment by kingardor** [comment]
Hi @rohitnairkp. Thanks! I can take up your request and work on a sample application. Meanwhile, if you have deepstream installed, you can go to `/opt/nvidia/deepstream/deepstream/sources/apps/sample_apps/deepstream-infer-tensor-meta-test` and refer this as an example.
